### ISSUE TITLE
GingerIt library is no longer available

### ISSUE THREAD

**Issue by eshanrajapakshe** [dgovor/Sign-Language-Translator#1]
GingerIt is not available for install.

**Comment by dgovor** [comment]
Hello Eshan,

Thank you very much for letting me know about this issue. On the moment I was writing the code for this project there were no issues installing Gingerit. However, I've just tried to reinstall it and it would give me a similar issue you experienced. I've submitted an error report to the authors of the library and am hoping the issue will get resolved soon. If the issue persists I will rewrite my code and will try to implement a different library with similar functions as Gingerit.

Thank you,
Dmitrii

**Comment by harshitsoni01** [comment]
Hello Dmitrii,
Is there any update on this?
The GingerIt is still not working.
Thanks & Regards,
Harshit Soni

**Comment by dgovor** [comment]
Hello Harshit,

My apologies for such a delay on this issue. The work has been getting pretty busy lately.
I have a library in mind that will be able to replace Gingerit. I've been testing it and it seems to be working well. I will push my latest update tomorrow or the day after tomorrow once I get a chance.

Thank you,
Dmitrii Govor

**Comment by dgovor** [comment]
Hello all,

I am excited to announce that I've just pushed an update for the main.py file that replaces the no longer available Gingerit library with the language_tool_python library that operates similarly. The only new prerequisite, besides installing language_tool_python, is ensuring you have Java 8.0+.
Please let me know if you have any questions.

Thank you,
Dmitrii Govor
