### ISSUE TITLE
Issue with Gingerit

### ISSUE THREAD

**Issue by SmokeySun** [dgovor/Sign-Language-Translator#2]
Gingerit is not available for download.

**Comment by dgovor** [comment]
Hello there,

Thank you very much for letting me know about this issue. On the moment I was writing the code for this project there were no issues installing Gingerit. However, as of today, the library is no longer available. I tried to contact the authors of the library but, unfortunately, did not receive a response. I have a library in mind that will be able to replace Gingerit. I've been testing it and it seems to be working well. I will push my latest update tomorrow or the day after tomorrow once I get a chance.

Thank you,
Dmitrii Govor
